import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  return (
    <html lang="en">
      <body>

        <header
          style={{
            background:"#0f172a",
            color:"white",
            padding:"16px 40px",
            display:"flex",
            alignItems:"center"
          }}
        >

          <img
            src="/aikym-logo.png"
            alt="AIKYM"
            style={{height:"40px",marginRight:"12px"}}
          />

          <h2 style={{margin:0}}>AI-KYM AI Readiness Assessment</h2>

        </header>

        {children}

      </body>
    </html>
  );
}
